### ISSUE TITLE
Can't find numpy/arrayobject.h

### ISSUE THREAD

**Issue by ghost** [naibaf7/PyGreentea#8]
Hello,

In addition to the "usual" [two](https://github.com/BVLC/caffe/issues/2347) [bugs](https://github.com/NVIDIA/DIGITS/issues/156) with libhdf5, I hit another irritating roadblock.

So, after installing dependencies, and setting caffe to auto-download in the config.py script (maybe this should be the default?), I eventually hit an error about not finding numpy/arraybuffer.h:

```
==== PYGT: Compiling Caffe/Greentea ============================================
make: Nothing to be done for 'all'.
CXX/LD -o python/caffe/_caffe.so python/caffe/_caffe.cpp
python/caffe/_caffe.cpp:12:36: fatal error: shim/numpy/arrayobject.h: No such file or directory
compilation terminated.
Makefile:627: recipe for target 'python/caffe/_caffe.so' failed
make: *** [python/caffe/_caffe.so] Error 1
```

I've tried a few things to fix this, hackishly, like making symlinks to what I *think* it's looking for, and changing `_caffe.cpp` so it points to the header file as an absolute path, but the C preprocessor isn't my forté and I can't get past this error. :/

My numpy includes:

```python
In [1]: import numpy
In [2]: numpy.get_include()
Out[2]: '/usr/local/lib/python3.5/dist-packages/numpy/core/include'
```

Would appreciate help getting this alive, I'd love to start using Caffe on OpenCL but the installation instructions for the opencl branch on caffe are..minimal, and this glue script doesn't seem to work correctly in its current state on Ubuntu 16.04.

Also, the caffe makefile.config appears to point to Python2.7, where it should probably be using some modern version of Python. Changing this didn't affect the above bug.

Thanks!

**Comment by naibaf7** [comment]
@cathalgarvey 
It seems your problems are not specifically with the PyGreentea/Caffe code.
So first note that PyGreentea is not a requirement for OpenCL Caffe, just a tool to make dense labeling tasks (network generation and data processing) with Caffe easier.

Python2.7 dependency is inherited from mainline Caffe. A compability port to Python3 is not completely done yet.

The package requirements for Ubuntu 16.04 are the following:
```
'git', 'gcc', 'libprotobuf-dev', 'libleveldb-dev',
                    'libsnappy-dev', 'libopencv-dev', 'libboost-all-dev',
                    'libhdf5-serial-dev', 'protobuf-compiler', 'gfortran',
                    'libjpeg62', 'libfreeimage-dev', 'libatlas-base-dev',
                    'libopenblas-base', 'libopenblas-dev', 'libgoogle-glog-dev',
                    'libbz2-dev', 'libxml2-dev', 'libxslt-dev', 'libffi-dev',
                    'libssl-dev', 'libgflags-dev', 'liblmdb-dev', 'python-dev',
'python-pip', 'python-yaml', 'libviennacl-dev', 'opencl-headers'
```
Then, you should probably try to install Numpy using PIP from your Python2.7 installation. It seems like Python3.5/2.7 is mixed up in your setup. Alternatively try to create a Python2.7 Anaconda environment. The header file that the compiler fails to find seems to be located here:
`/usr/lib/python2.7/site-packages/numpy/core/include/`

**Comment by ghost** [comment]
Hi, thanks for the quick response.

My Py2/Py3 setup isn't mixed at all, I'm happy to say. In both cases, the Python core is installed via apt, and most modules are then installed via pip, and they go to the correct subdirs.

However, if I'd changed enough code to attempt a (doomed) Py3 build, perhaps there is some hard-coded temporary makefile pointing still at Py2, or something.

In any case, I'm not really interested in getting this set up on Py2, so I'll return later when things are a bit more solid on the Py3 end. Thanks for your efforts on this, I'm eager to see OpenCL support more widespread in the ML community!

**Comment by naibaf7** [comment]
@cathalgarvey 
Thanks for your comment.
Yes hmm, you seem not too unfamiliar to python, so it's strange this can't be worked out.
Happy to report I tested it again on a very "virgin" Ubuntu 16.04 installation today (VM with GPU passthrough) and it worked very well, although with Python2.7.
As you are a coder yourself we might be able to schedule a Skype session to figure out how to get it running with Python3, if you wish to use it earlier.
Otherwise you can also try a setup independent of PyGreentea first.
Someone seems to have had success using Pyton3.5 with the Caffe master branch.
That means it must also work with OpenCL Caffe, there are no breaking changes to the PyCaffe interface.
Reference: https://gist.github.com/alexlee-gk/ba07524dc0d972be9eac

My recommended installation configuration for you if you want only OpenCL dependence would then be:
- Install with clBLAS, choose as default OpenCL BLAS
- Enable USE_LIBDNN
- Enable USE_GREENTEA
- Disable USE_INDEX64, USE_CUDNN and USE_CUDA
- Use ViennaCL from here: https://github.com/viennacl/viennacl-dev (no need to compile)

**Comment by ghost** [comment]
Hmm, I'd assumed the compatibility issue lay with the C/OpenCL end of things. If you mean that this is an issue that can be resolved with Python, perhaps I can help. 

Although, there's a lot of build/make in this which I'm not so good at. It seems to me that the challenge with C isn't so much the (relatively simple) language, but with the convoluted build platforms and OS search path stuff. :)

I don't use Skype but am happy to either discuss here /over chat or find time on meet.jit.si to see where I might be of use.

On 23 November 2016 22:52:16 GMT+00:00, Fabian Tschopp <notifications@github.com> wrote:
>@cathalgarvey 
>Thanks for your comment.
>Yes hmm, you seem not too unfamiliar to python, so it's strange this
>can't be worked out.
>Happy to report I tested it again on a very "virgin" Ubuntu 16.04
>installation today (VM with GPU passthrough) and it worked very good.
>As you are a coder yourself we might be able to schedule a Skype
>session to figure out how to get it running with Python3, if you wish
>to use it earlier.
>Otherwise you can also try a setup independent of PyGreentea first.
>Someone seems to have had success using Pyton3.5 with the Caffe master
>branch.
>That means it must also work with OpenCL Caffe, there are no breaking
>changes to the PyCaffe interface.
>Reference: https://gist.github.com/alexlee-gk/ba07524dc0d972be9eac
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/naibaf7/PyGreentea/issues/8#issuecomment-262649420

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by naibaf7** [comment]
@cathalgarvey 
Well core Caffe does not require any Python dependencies, i.e. a test build with the Make system should work for you:
```
make all -j4;
make runtest -j4;
make pycaffe -j4;
```
The last line should be (at most) failing. If so, we should be able to debug that.
